import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, CircleDot, ClipboardCheck, Database, Gauge, GitBranch, RotateCcw, Scale, Send, ShieldCheck, UserRoundCheck, Workflow } from "lucide-react";
import { SiteHeader } from "@/components/site-header";

export const metadata:Metadata={title:"Product Case Study",description:"How Mission Control evolved into a population-level operating system for inspectable and governed AI workflows."};

const principles=[
  ["01","Start from the operator’s population.","Retention screens members, moderation screens posts, and event growth screens events. No workflow begins with a permanently selected demo person."],
  ["02","Make every boundary inspectable.","Source, scoring, context, agent, policy, review, and action stages expose different outputs and different limits."],
  ["03","Use models selectively.","Claude interprets ambiguous context and drafts relevant work. Reproducible scoring, permissions, policy, and release remain outside the model."],
  ["04","Stop where authority changes.","The workflow reaches Human Review and waits. An approved draft—not an unreviewed recommendation—moves to action history."],
  ["05","Make governance operational.","Publishing a policy version recalculates active queues; rules are controls that change state, not static documentation."],
  ["06","Keep prototype claims honest.","Runs, records, and released actions are synthetic or simulated and labeled as such."],
];

const surfaces=[
  [Workflow,"Overview","Session-derived operating state: runs, screened records, exceptions, and released actions."],
  [GitBranch,"Workflows","Sequential population runs with live sub-operations and stage-specific inspection."],
  [ClipboardCheck,"Human review","One governed queue with evidence, escalation reason, editable copy, and approve/reject controls."],
  [ShieldCheck,"Governance","Publish reusable confidence and bulk-review rules and recalculate active queues."],
  [RotateCcw,"Reset demo","Return the session to zero without changing environment or provider configuration."],
];

export default function CaseStudy(){return <main className="bg-[#fbfdff]">
  <SiteHeader/>
  <section className="relative overflow-hidden border-b border-[#d9e5ef] bg-[#10253f] py-20 text-white sm:py-28"><div className="absolute right-[-10%] top-[-40%] size-[620px] rounded-full border-[110px] border-[#1263e6]/25"/><div className="page-shell relative"><div className="flex flex-wrap items-center gap-3"><span className="rounded-full border border-white/20 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.1em] text-[#8ddcf8]">Product case study</span><span className="text-[10px] text-white/45">Independent concept · Current prototype</span></div><h1 className="mt-8 max-w-5xl text-balance text-[44px] font-semibold leading-[.98] tracking-[-.055em] sm:text-[74px]">From one AI recommendation to an operating system for governed work.</h1><p className="mt-8 max-w-3xl text-lg leading-8 text-white/62">Mission Control now demonstrates the full operating loop: screen a population, watch bounded stages run, inspect each result, apply deterministic authority rules, review exact drafts, release simulated actions, and reset the session.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/studio" className="focus-ring inline-flex h-12 items-center gap-2 rounded-full bg-[#65cef2] px-6 text-sm font-semibold text-[#0b2841]">Open the working product <ArrowRight size={16}/></Link><Link href="#current-product" className="focus-ring inline-flex h-12 items-center rounded-full border border-white/25 px-6 text-sm font-semibold">See what changed</Link></div></div></section>

  <section className="border-b border-[#dce6ef] bg-white py-10"><div className="page-shell grid gap-7 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Project" value="Mission Control"/><Fact label="Demo customer" value="Northstar Professional Association · Fictional"/><Fact label="Product shape" value="Population workflow control plane"/><Fact label="Built scope" value="Product strategy · UX · Architecture · Prototype"/></div></section>

  <section className="py-24 sm:py-32"><div className="page-shell grid gap-14 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#1263e6]">Starting question</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">A platform question, not a chatbot question.</h2></div><div className="max-w-2xl text-[17px] leading-8 text-[#5a6f83]"><p>The public MomentiveIQ direction and the R506 role description point toward agents that connect existing systems, interpret signals, automate workflows, and preserve human oversight. I treated those public signals as product constraints—not as knowledge of Momentive’s internal architecture or roadmap.</p><p className="mt-6 font-semibold text-[#10253f]">The resulting question: what operating layer would a product team need to scale useful agents across retention, community, and events without hiding context, authority, or failure?</p></div></div></section>

  <section id="current-product" className="border-y border-[#dbe6ef] bg-[#edf6ff] py-24 sm:py-32"><div className="page-shell"><p className="eyebrow text-[#f36f56]">How the prototype matured</p><h2 className="mt-5 max-w-4xl text-balance text-4xl font-semibold leading-[1.05] tracking-[-.04em] sm:text-6xl">Four product corrections turned the concept into a coherent operating flow.</h2><div className="mt-16 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["01","One member → managed population","The operator now sees every scoped record, ranked exceptions, blocked cases, and the review queue. Sarah is one case—not the product."],["02","Generic inspector → stage truth","Selecting a node changes the queue, metrics, evidence, trace, rules, consequence, and explanation for that operating boundary."],["03","Instant completion → observable execution","Each stage performs three visible sub-operations. Later stages wait, failures stop safely, and the run ends at human authority."],["04","Internal directive → recipient copy","Findings and recommendations remain internal. The reviewer edits a separate outward-facing draft, and unsafe operational language cannot be released."]].map(item=><div key={item[0]} className="rounded-[24px] border border-[#cfdfea] bg-white p-6 surface-shadow"><span className="font-mono text-xs text-[#1263e6]">{item[0]}</span><h3 className="mt-8 text-lg font-semibold">{item[1]}</h3><p className="mt-3 text-sm leading-6 text-[#627689]">{item[2]}</p></div>)}</div></div></section>

  <section className="bg-white py-24 sm:py-32"><div className="page-shell"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><p className="eyebrow text-[#7a69d8]">Current product</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Five connected surfaces, one session state.</h2></div><p className="max-w-2xl text-lg leading-8 text-[#5a6f83] lg:justify-self-end">The Studio is designed as an operating product rather than a gallery of disconnected dashboards. A workflow run populates Overview and Human Review. Governance can recalculate the queue. Approved content appears in action history. Reset clears it all.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{surfaces.map(([Icon,title,copy])=><div key={String(title)} className="rounded-2xl border border-[#d8e3ec] bg-[#fbfdff] p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#eaf3ff] text-[#1263e6]"><Icon size={17}/></span><h3 className="mt-6 text-sm font-semibold">{title as string}</h3><p className="mt-2 text-xs leading-6 text-[#667b8e]">{copy as string}</p></div>)}</div></div></section>

  <section className="bg-[#10253f] py-24 text-white sm:py-32"><div className="page-shell"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#67d1f4]">Operating model</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Population in. Approved action out.</h2><p className="mt-5 text-base leading-7 text-white/58">Each boundary has one owner and one kind of authority.</p></div><div className="overflow-x-auto"><div className="grid min-w-[760px] grid-cols-7 gap-2">{[[Database,"Population","Read"],[Gauge,"Scoring","Rank"],[Database,"Context","Ground"],[GitBranch,"Claude","Recommend"],[Scale,"Policy","Route"],[UserRoundCheck,"Human","Authorize"],[Send,"Action","Release"]].map(([Icon,label,authority],index)=><div key={String(label)} className="relative text-center">{index<6&&<ArrowRight className="absolute -right-4 top-6 text-white/25" size={15}/>}<span className="mx-auto grid size-12 place-items-center rounded-xl bg-white/9 text-[#6bd3f7]"><Icon size={18}/></span><p className="mt-4 text-xs font-semibold">{label as string}</p><p className="mt-1 text-[9px] uppercase tracking-[.08em] text-white/42">{authority as string}</p></div>)}</div></div></div><div className="mt-16 grid gap-3 lg:grid-cols-3">{[["Membership Retention","12 members","5 attention · 1 blocked · 4 review","Relevant member outreach"],["Community Moderation","10 posts","4 flagged","Approved reversible moderation"],["Event Growth","6 events","3 opportunities","Approved campaign activation"]].map(row=><div key={row[0]} className="rounded-2xl border border-white/12 bg-white/[.035] p-5"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">{row[0]}</h3><span className="rounded-full bg-white/10 px-2.5 py-1 text-[9px] text-[#83daf6]">{row[1]}</span></div><p className="mt-5 text-xs font-semibold text-white/75">{row[2]}</p><p className="mt-2 text-[10px] text-white/45">Outcome: {row[3]}</p></div>)}</div></div></section>

  <section className="border-y border-[#dce6ef] bg-[#f8fbfe] py-24 sm:py-32"><div className="page-shell grid gap-16 lg:grid-cols-[.65fr_1.35fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow text-[#1263e6]">Product principles</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Six constraints visible in the interface.</h2></div><div className="divide-y divide-[#d9e4ed] border-y border-[#d9e4ed]">{principles.map(principle=><div key={principle[0]} className="grid grid-cols-[45px_1fr] gap-4 py-7 sm:grid-cols-[60px_220px_1fr]"><span className="font-mono text-[10px] text-[#1263e6]">{principle[0]}</span><h3 className="text-base font-semibold">{principle[1]}</h3><p className="mt-2 text-sm leading-6 text-[#64788b] sm:mt-0">{principle[2]}</p></div>)}</div></div></section>

  <section id="architecture" className="bg-white py-24 sm:py-32"><div className="page-shell grid gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow text-[#7a69d8]">Architecture decision</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Why hybrid.</h2><p className="mt-5 text-base leading-7 text-[#5d7185]">A single agent is cheaper and faster, while multiple agents can specialize. Neither tradeoff alone answers who may act. Hybrid creates explicit system boundaries around targeted model reasoning.</p></div><div className="space-y-3">{[["Population intake","Connector / API","Reads only workflow-scoped synthetic records."],["Scoring + classification","Deterministic","Produces reproducible priority and risk bands."],["Context assembly","Connector / service","Builds the only evidence package passed forward."],["Recommendation + drafting","Claude","Interprets ambiguity; cannot authorize or release."],["Policy gate","Deterministic","Applies confidence, consent, consequence, and bulk rules."],["Review + release","Human + action service","Persists the exact authorized action and content."]].map((row,index)=><div key={row[0]} className="grid gap-2 rounded-xl border border-[#dce5ed] p-4 sm:grid-cols-[155px_145px_1fr]"><p className="text-xs font-semibold">{row[0]}</p><span className={`w-fit rounded-full px-2 py-1 text-[9px] font-semibold ${index===3?"bg-[#eeeafe] text-[#6652bb]":index===5?"bg-[#fff0ed] text-[#b84d3a]":"bg-[#eaf3ff] text-[#1263e6]"}`}>{row[1]}</span><p className="text-[10px] leading-5 text-[#63778a]">{row[2]}</p></div>)}</div></div></section>

  <section className="bg-white py-24 sm:py-32"><div className="page-shell"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#f36f56]">Human and policy control</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Recommendation is not authorization.</h2></div><div className="text-lg leading-8 text-[#5a6f83]"><p>The agent can prepare an intervention and exact message. Policy then decides whether the record is blocked, eligible for grouped human approval, or requires an individual decision. Only the reviewer releases the work.</p><p className="mt-5 font-semibold text-[#10253f]">That separation is visible in stage inspection, configurable in Governance, and preserved in action history.</p></div></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{[[ShieldCheck,"Blocked","Missing consent, missing critical evidence, or confidence below the action floor stops the case."],[ClipboardCheck,"Grouped approval","High-confidence, reversible, non-financial items may be approved together by one reviewer."],[UserRoundCheck,"Individual approval","Financial offers, consequential moderation, and ambiguous work require case-by-case judgment."]].map(([Icon,title,copy])=><div key={String(title)} className="rounded-2xl border border-[#dce5ed] p-5"><Icon size={19} className="text-[#1263e6]"/><h3 className="mt-6 text-sm font-semibold">{title as string}</h3><p className="mt-3 text-xs leading-6 text-[#677b8e]">{copy as string}</p></div>)}</div></div></section>

  <section className="border-t border-[#dce6ef] bg-[#fbfdff] py-24"><div className="page-shell"><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-[28px] border border-[#f0c5bc] bg-[#fff4f1] p-7 sm:p-9"><p className="eyebrow text-[#c6543f]">Current limitations</p><div className="mt-7 space-y-4">{["No production customer systems or real member data are connected.","Messages, moderation actions, and campaigns are simulated rather than externally executed.","Session state is held in memory; there is no authentication, role model, or durable database.","The prototype does not claim real conversion, revenue, productivity, latency, or cost outcomes."].map(item=><div key={item} className="flex gap-3"><CircleDot size={15} className="mt-1 shrink-0 text-[#d4614c]"/><p className="text-sm leading-6">{item}</p></div>)}</div></div><div className="rounded-[28px] border border-[#cbddeb] bg-[#f1f7ff] p-7 sm:p-9"><p className="eyebrow text-[#1263e6]">What a pilot must validate</p><div className="mt-7 space-y-4">{["Which workflow creates enough operator value to justify integration?","Which evidence makes a recommendation trustworthy and actionable?","Where do false positives and false escalations create operational burden?","Which roles may approve each action class, and what audit record is required?"].map(item=><div key={item} className="flex gap-3"><Check size={15} className="mt-1 shrink-0 text-[#338355]"/><p className="text-sm leading-6">{item}</p></div>)}</div></div></div><div className="mt-10 rounded-xl border border-[#dce5ed] bg-white p-5 text-xs leading-6 text-[#63778a]"><strong className="text-[#10253f]">Disclaimer:</strong> This is an independent product exploration created from publicly available information. It is not affiliated with, endorsed by, or based on confidential information from Momentive Software.</div></div></section>

  <section className="bg-[#1263e6] py-20 text-white"><div className="page-shell flex flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow text-[#bceaff]">Explore the prototype</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Run the product argument yourself.</h2></div><Link href="/studio" className="focus-ring inline-flex h-12 items-center gap-2 rounded-full bg-white px-6 text-sm font-semibold text-[#1152b5]">Open Mission Control <ArrowRight size={16}/></Link></div></section>
  <footer className="bg-[#0b1d31] py-8 text-white"><div className="page-shell flex flex-wrap justify-between gap-4 text-xs"><span>Akash Sangami · Independent product concept</span><div className="flex gap-5 text-white/60"><a href="mailto:sangami.akash@gmail.com">Email</a><a href="https://www.linkedin.com/in/akashsangami/">LinkedIn</a></div></div></footer>
</main>}

function Fact({label,value}:{label:string;value:string}){return <div><p className="text-[9px] font-bold uppercase tracking-[.12em] text-[#7b8d9e]">{label}</p><p className="mt-2 text-sm font-semibold">{value}</p></div>}
