"use client";

import { Check, Database, FileClock, KeyRound, LockKeyhole, Save, Scale, ShieldCheck, SlidersHorizontal, UserRoundCheck, Workflow as WorkflowIcon } from "lucide-react";
import { useMemo, useState } from "react";
import { Badge } from "./cohort-workflow";
import { applyGovernanceToRun, getWorkflowFixture, type GovernanceConfig, type WorkflowDomainId, type WorkflowRun } from "@/lib/workflow-domain";

const workflowNames:Record<WorkflowDomainId,string>={"membership-retention":"Membership Retention","community-moderation":"Community Moderation","event-growth":"Event Growth"};

export function GovernanceControlPlane({config,version,runs,onPublish}:{config:GovernanceConfig;version:number;runs:Partial<Record<WorkflowDomainId,WorkflowRun>>;onPublish:(config:GovernanceConfig)=>void}){
  const [draft,setDraft]=useState(config);
  const changed=JSON.stringify(draft)!==JSON.stringify(config);
  const sourceRuns=useMemo(()=>{const available=Object.values(runs).filter(Boolean) as WorkflowRun[];return available.length?available:(Object.keys(workflowNames) as WorkflowDomainId[]).map(getWorkflowFixture)},[runs]);
  const projected=sourceRuns.map(run=>applyGovernanceToRun(run,draft));
  const candidates=projected.flatMap(run=>run.candidates);
  const pending=candidates.filter(candidate=>candidate.status==="pending_review");
  const bulk=pending.filter(candidate=>candidate.policy.outcome==="bulk_eligible");
  const individual=pending.filter(candidate=>candidate.policy.outcome==="individual_review");
  const blocked=candidates.filter(candidate=>candidate.status==="blocked");
  return <>
    <div className="mb-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#1263e6]">Governance control plane</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Define authority outside the model.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#66798c]">Set the rules that route work to individual review, grouped approval, or a blocked state. Preview the effect before publishing one policy version across all workflows.</p></div><button data-testid="publish-policy" onClick={()=>onPublish(draft)} disabled={!changed} className="focus-ring flex h-10 items-center gap-2 rounded-xl bg-[#1263e6] px-4 text-xs font-semibold text-white disabled:bg-[#a9b9c8]"><Save size={14}/>Publish policy v3.{version+1}</button></div>

    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[
      [ShieldCheck,"Active policy",`v3.${version}`,changed?"Draft changes not published":"Applied to all workflows"],
      [UserRoundCheck,"Individual approval",String(individual.length),"One decision per item"],
      [WorkflowIcon,"Grouped approval",String(bulk.length),draft.bulkApprovalEnabled?`Eligible at ≥${draft.bulkApprovalConfidence}%`:"Grouped approval disabled"],
      [LockKeyhole,"Blocked",String(blocked.length),`Cannot enter review or release`],
    ].map(([Icon,label,value,detail])=><section key={String(label)} className="rounded-2xl border border-[#dbe5ed] bg-white p-4 sm:p-5"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-[#edf5ff] text-[#1263e6]"><Icon size={16}/></span><span className="max-w-[110px] text-right text-[9px] leading-4 text-[#8292a2]">{detail as string}</span></div><p className="mt-5 font-mono text-2xl font-semibold">{value as string}</p><p className="mt-1 text-[10px] text-[#6f8294]">{label as string}</p></section>)}</div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[.8fr_1.2fr]">
      <section className="rounded-2xl border border-[#dbe4ec] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Review routing rules</h2><p className="mt-1 text-[10px] text-[#788a9b]">Draft changes · publish to apply</p></div><SlidersHorizontal size={17} className="text-[#1263e6]"/></div><div className="mt-6"><div className="flex items-end justify-between gap-5"><div><label htmlFor="block-confidence" className="text-xs font-semibold">Minimum confidence to enter review</label><p className="mt-1 text-[9px] leading-4 text-[#76899a]">A recommendation below this score is blocked. It cannot create a review item or be released.</p></div><span className="shrink-0 font-mono text-2xl font-semibold">{draft.blockBelowConfidence}%</span></div><input id="block-confidence" type="range" min="50" max="85" step="5" value={draft.blockBelowConfidence} onChange={event=>setDraft(current=>({...current,blockBelowConfidence:Number(event.target.value)}))} className="mt-4 w-full accent-[#1263e6]"/></div><div className="mt-7 border-t border-[#e5ebf0] pt-6"><div className="flex items-end justify-between gap-5"><div><label htmlFor="bulk-confidence" className="text-xs font-semibold">Minimum confidence for grouped approval</label><p className="mt-1 text-[9px] leading-4 text-[#76899a]">At or above this score, eligible low-impact items may be approved together. Financial and consequential work always stays individual.</p></div><span className="shrink-0 font-mono text-2xl font-semibold">{draft.bulkApprovalConfidence}%</span></div><input id="bulk-confidence" type="range" min="85" max="100" step="1" value={draft.bulkApprovalConfidence} onChange={event=>setDraft(current=>({...current,bulkApprovalConfidence:Number(event.target.value)}))} className="mt-4 w-full accent-[#1263e6]"/></div><label className="mt-7 flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-[#dce5ed] bg-[#f8fafc] p-4"><div><p className="text-xs font-semibold">Enable grouped approval for eligible items</p><p className="mt-1 text-[9px] leading-4 text-[#718496]">Lets a reviewer approve several high-confidence, reversible, non-financial items in one decision. Every item still receives human approval.</p></div><input type="checkbox" checked={draft.bulkApprovalEnabled} onChange={event=>setDraft(current=>({...current,bulkApprovalEnabled:event.target.checked}))} className="mt-1 size-4 accent-[#1263e6]"/></label>{changed&&<div role="status" className="mt-5 rounded-xl border border-[#ecd49e] bg-[#fff8e8] p-3 text-[10px] leading-5 text-[#776036]">These changes are only a preview. Publish the policy version to update active workflow queues.</div>}</section>

      <section className="overflow-hidden rounded-2xl border border-[#dbe4ec] bg-white"><div className="flex items-center justify-between border-b border-[#e4eaf0] p-5"><div><h2 className="text-sm font-semibold">Review queue preview</h2><p className="mt-1 text-[10px] text-[#7d8f9f]">{Object.values(runs).some(Boolean)?"Calculated from workflows run this session":"Calculated from all synthetic workflow fixtures"}</p></div><Scale size={17} className="text-[#c7821b]"/></div><div className="grid grid-cols-3 gap-px bg-[#e4eaf0]"><div className="bg-[#eff9f2] p-4"><p className="text-[8px] font-bold uppercase tracking-[.08em] text-[#4c8160]">Grouped approval</p><p className="mt-2 font-mono text-2xl font-semibold text-[#2f7448]">{bulk.length}</p></div><div className="bg-[#fff8e9] p-4"><p className="text-[8px] font-bold uppercase tracking-[.08em] text-[#8b671e]">Individual approval</p><p className="mt-2 font-mono text-2xl font-semibold text-[#7d5c1c]">{individual.length}</p></div><div className="bg-[#f4f6f8] p-4"><p className="text-[8px] font-bold uppercase tracking-[.08em] text-[#687a8c]">Blocked</p><p className="mt-2 font-mono text-2xl font-semibold">{blocked.length}</p></div></div><div className="divide-y divide-[#e7edf2]">{projected.map(run=>{const runPending=run.candidates.filter(candidate=>candidate.status==="pending_review");const runBlocked=run.candidates.filter(candidate=>candidate.status==="blocked");return <div key={run.workflowId} className="grid grid-cols-[1fr_auto] gap-4 p-5"><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold">{workflowNames[run.workflowId]}</p><Badge>{run.screened} screened</Badge></div><p className="mt-2 text-[10px] text-[#718496]">{runPending.filter(candidate=>candidate.policy.outcome==="bulk_eligible").length} grouped · {runPending.filter(candidate=>candidate.policy.outcome==="individual_review").length} individual · {runBlocked.length} blocked</p></div><div className="flex -space-x-1">{runPending.slice(0,4).map(candidate=><span key={candidate.id} title={candidate.title} className="grid size-7 place-items-center rounded-full border-2 border-white bg-[#e7f1ff] text-[8px] font-bold text-[#1263e6]">{candidate.title.split(" ").map(part=>part[0]).join("").slice(0,2)}</span>)}</div></div>})}</div><div className="border-t border-[#e4eaf0] bg-[#f8fafc] p-4 text-[10px] leading-5 text-[#64788b]"><strong className="text-[#10253f]">What publishing changes:</strong> thresholds only change whether work is blocked, routed to individual review, or eligible for grouped human approval. Claude never receives permission to release an action.</div></section>
    </div>

    <section className="mt-6 overflow-hidden rounded-2xl border border-[#dbe4ec] bg-white"><div className="flex items-center justify-between border-b border-[#e4eaf0] p-5"><div><h2 className="text-sm font-semibold">Tool and data permissions</h2><p className="mt-1 text-[10px] text-[#7d8f9f]">Least-privilege scopes by workflow; outward actions remain human-gated</p></div><KeyRound size={17} className="text-[#1263e6]"/></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-[10px]"><thead className="bg-[#f7f9fb] text-[8px] uppercase tracking-[.08em] text-[#7d8e9f]"><tr><th className="p-4">Workflow</th><th className="p-4">Read scope</th><th className="p-4">Model-assisted capability</th><th className="p-4">Prohibited without human</th><th className="p-4">Failure behavior</th></tr></thead><tbody className="divide-y divide-[#e7edf2]">{[
          ["Membership Retention","Member, event, learning, community aggregates","Interpret shifts; draft outreach","Send message; release financial offer","Hold outreach and preserve evidence"],
          ["Community Moderation","Post, thread context, applicable policy","Classify; compare policy evidence","Ban user; apply consequential sanction","Restrict no content without policy result"],
          ["Event Growth","Event capacity, audience aggregates, consent","Recommend campaign and copy","Export audience; activate financial offer","Do not create or activate campaign"],
        ].map(row=><tr key={row[0]}>{row.map((cell,index)=><td key={cell} className={`p-4 leading-5 ${index===0?"font-semibold":"text-[#60758a]"}`}>{cell}</td>)}</tr>)}</tbody></table></div></section>

    <div className="mt-6 grid gap-6 lg:grid-cols-3">{[
      [LockKeyhole,"Always individual","Financial offers, threats, bans, and other consequential actions cannot be bulk approved."],
      [Database,"Consent and evidence required","Missing critical evidence or communication authority blocks the action before release."],
      [FileClock,"Audit is mandatory","Input evidence, policy version, reviewer, edits, final action, and timestamp are recorded together."],
    ].map(([Icon,title,copy])=><section key={String(title)} className="rounded-2xl border border-[#dbe4ec] bg-white p-5"><span className="grid size-9 place-items-center rounded-xl bg-[#edf5ff] text-[#1263e6]"><Icon size={16}/></span><h2 className="mt-5 text-sm font-semibold">{title as string}</h2><p className="mt-2 text-[10px] leading-5 text-[#667b8e]">{copy as string}</p><div className="mt-4 flex items-center gap-2 text-[9px] font-semibold text-[#358056]"><Check size={12}/>Enforced outside Claude</div></section>)}</div>
  </>;
}
