"use client";

import { ArrowRight, Bot, Check, CircleAlert, Clock3, Send, UsersRound, Workflow as WorkflowIcon } from "lucide-react";
import { Badge } from "./cohort-workflow";
import type { Workflow } from "@/lib/types";
import type { ActionRecord, WorkflowDomainId, WorkflowRun } from "@/lib/workflow-domain";

type View="overview"|"workflow"|"governance"|"review";

export function OperationsOverview({workflows,runs,actions,onChoose,onNavigate}:{workflows:Workflow[];runs:Partial<Record<WorkflowDomainId,WorkflowRun>>;actions:ActionRecord[];onChoose:(workflow:Workflow)=>void;onNavigate:(view:View)=>void}){
  const completedRuns=Object.values(runs).filter(Boolean) as WorkflowRun[];
  const screened=completedRuns.reduce((sum,run)=>sum+run.screened,0);
  const pending=completedRuns.flatMap(run=>run.candidates.filter(candidate=>candidate.status==="pending_review"));
  const blocked=completedRuns.flatMap(run=>run.candidates.filter(candidate=>candidate.status==="blocked"));
  const nextWorkflow=workflows.find(workflow=>!runs[workflow.id as WorkflowDomainId])??workflows[0];
  return <>
    <div className="mb-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#1263e6]">Operations overview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">{completedRuns.length?"Your AI workflows need attention.":"Your operating session is ready."}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#66798c]">{completedRuns.length?`${completedRuns.length} of 3 workflows ran this session. ${pending.length} decisions require judgment before any external action is released.`:"Screen a real operating population, inspect the exceptions, and release only approved actions."}</p></div><button onClick={()=>pending.length?onNavigate("review"):onChoose(nextWorkflow)} className="focus-ring flex h-11 items-center justify-center gap-2 rounded-xl bg-[#1263e6] px-5 text-xs font-semibold text-white hover:bg-[#0d54c7]">{pending.length?`Review ${pending.length} decisions`:`Run ${nextWorkflow.name}`}<ArrowRight size={14}/></button></div>

    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[
      [WorkflowIcon,"Workflows run",`${completedRuns.length} / 3`,completedRuns.length===3?"Portfolio screened":"This session"],
      [UsersRound,"Records screened",String(screened),screened?"Across active runs":"Awaiting first run"],
      [CircleAlert,"Needs judgment",String(pending.length),blocked.length?`${blocked.length} additional blocked`:"No unsafe release"],
      [Send,"Actions released",String(actions.length),"Simulated and audited"],
    ].map(([Icon,label,value,detail])=><section key={String(label)} className="rounded-2xl border border-[#dbe5ed] bg-white p-4 sm:p-5"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-[#edf5ff] text-[#1263e6]"><Icon size={16}/></span><span className="text-right text-[9px] text-[#8292a2]">{detail as string}</span></div><p className="mt-5 font-mono text-2xl font-semibold">{value as string}</p><p className="mt-1 text-[10px] text-[#6f8294]">{label as string}</p></section>)}</div>

    <div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]">
      <section className="overflow-hidden rounded-2xl border border-[#dce5ed] bg-white"><div className="flex items-center justify-between border-b border-[#e2e9ef] px-5 py-4"><div><h2 className="text-sm font-semibold">Workflow portfolio</h2><p className="mt-1 text-[10px] text-[#8191a1]">Operational state from this browser session—not invented historical KPIs</p></div><Badge>{completedRuns.length} run</Badge></div><div className="divide-y divide-[#e5ebf0]">{workflows.map((workflow,index)=>{const id=workflow.id as WorkflowDomainId;const run=runs[id];const workflowPending=run?.candidates.filter(candidate=>candidate.status==="pending_review").length??0;const workflowBlocked=run?.candidates.filter(candidate=>candidate.status==="blocked").length??0;const workflowActions=actions.filter(action=>action.workflowId===id).length;return <button key={workflow.id} onClick={()=>onChoose(workflow)} className="focus-ring grid w-full grid-cols-[auto_1fr_auto] items-center gap-4 p-5 text-left hover:bg-[#f8fbff]"><span className={`grid size-11 place-items-center rounded-xl ${index===0?"bg-[#eaf3ff] text-[#1263e6]":index===1?"bg-[#e9f8f4] text-[#27856d]":"bg-[#fff3e1] text-[#ad6d12]"}`}><WorkflowIcon size={18}/></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{workflow.name}</h3><Badge tone={run?"green":"gray"}>{run?"Run complete":"Not run"}</Badge></div><p className="mt-1 text-[10px] text-[#718496]">{run?`${run.screened} screened · ${workflowPending} pending · ${workflowBlocked} blocked · ${workflowActions} released`:workflow.objective}</p>{run&&<p className="mt-2 text-[9px] text-[#8a99a7]">{run.source==="claude"?run.model:"Safe fixture"} · session result</p>}</div><ArrowRight size={16} className="text-[#8ca0b2]"/></button>})}</div></section>

      <div className="space-y-6"><section className="rounded-2xl border border-[#ead5a7] bg-[#fffaf0] p-5"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-[#fff0cf] text-[#a87418]"><CircleAlert size={17}/></span><Badge tone={pending.length?"amber":"green"}>{pending.length} need review</Badge></div><h2 className="mt-5 text-lg font-semibold">{pending.length?`${pending.length} ${pending.length===1?"item needs":"items need"} your approval.`:"No reviews waiting."}</h2><p className="mt-2 text-xs leading-5 text-[#746647]">{pending.length?"Review each recommendation and recipient-facing message before it is released.":blocked.length?`${blocked.length} ${blocked.length===1?"record is":"records are"} blocked and cannot enter review until the missing requirements are resolved.`:"Run a workflow to create review items."}</p>{pending.length>0&&<div className="mt-4 space-y-2">{pending.slice(0,4).map(candidate=><div key={candidate.id} className="rounded-xl border border-[#eadfca] bg-white/75 p-3"><div className="flex items-center justify-between gap-2"><p className="truncate text-[10px] font-semibold">{candidate.title}</p><Badge tone="amber">Review</Badge></div><p className="mt-1 line-clamp-1 text-[9px] text-[#786b55]">{candidate.policy.reason}</p></div>)}</div>}<button onClick={()=>onNavigate(pending.length?"review":"workflow")} className="focus-ring mt-5 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#10253f] text-xs font-semibold text-white">{pending.length?"Open review inbox":blocked.length?"Inspect blocked records":"Run a workflow"}<ArrowRight size={14}/></button></section></div>
    </div>

    <section className="mt-6 overflow-hidden rounded-2xl border border-[#dbe5ed] bg-white"><div className="flex items-center justify-between border-b border-[#e4eaf0] p-4"><div><h2 className="text-sm font-semibold">Released action history</h2><p className="mt-1 text-[10px] text-[#7c8d9d]">Exact approved actions from this session</p></div><Clock3 size={17} className="text-[#8496a7]"/></div>{actions.length?<div className="divide-y divide-[#e7edf2]">{actions.slice(0,4).map(action=><div key={action.id} className="grid grid-cols-[28px_1fr_auto] gap-3 p-4"><span className="grid size-7 place-items-center rounded-full bg-[#eaf8ee] text-[#2f8050]"><Check size={13}/></span><div><p className="text-xs font-semibold">{action.title}</p><p className="mt-1 text-[10px] text-[#718496]">{action.action}</p></div><Badge tone="green">{action.status}</Badge></div>)}</div>:<div className="p-8 text-center"><Bot size={21} className="mx-auto text-[#91a2b2]"/><p className="mt-3 text-xs font-semibold">Nothing has been released</p><p className="mt-1 text-[10px] text-[#758799]">This is the correct state until a person approves an action.</p></div>}</section>
  </>;
}
