"use client";

import { AlertTriangle, Check, ClipboardCheck, Database, RotateCcw, Send, ShieldCheck, Workflow as WorkflowIcon, X } from "lucide-react";
import { useState } from "react";
import type { ActionRecord, WorkflowDomainId, WorkflowRun } from "@/lib/workflow-domain";

export function ResetDemoPage({runs,actions,governanceVersion,onReset}:{runs:Partial<Record<WorkflowDomainId,WorkflowRun>>;actions:ActionRecord[];governanceVersion:number;onReset:()=>void}){
  const [confirming,setConfirming]=useState(false);
  const completedRuns=Object.values(runs).filter(Boolean) as WorkflowRun[];
  const decisions=completedRuns.reduce((count,run)=>count+run.candidates.filter(candidate=>candidate.status==="pending_review"||candidate.status==="rejected").length,0);
  const changedPolicy=governanceVersion!==2;
  const clean=completedRuns.length===0&&actions.length===0&&!changedPolicy;
  const resetItems=[
    {icon:WorkflowIcon,label:"Workflow results",value:`${completedRuns.length} run${completedRuns.length===1?"":"s"}`,detail:"Screened populations, scores, evidence packages, and traces"},
    {icon:ClipboardCheck,label:"Review decisions",value:`${decisions} recorded or pending`,detail:"Pending approvals, rejections, and edited drafts"},
    {icon:Send,label:"Released actions",value:`${actions.length} action${actions.length===1?"":"s"}`,detail:"Simulated outreach, moderation actions, and activations"},
    {icon:ShieldCheck,label:"Governance policy",value:`v3.${governanceVersion}`,detail:changedPolicy?"Published thresholds will return to v3.2 defaults":"Already using the v3.2 defaults"},
  ];
  return <>
    <div className="mb-7"><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#1263e6]">Demo controls</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Return the workspace to its starting state.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#66798c]">Clear every result and decision created during this browser session so the demo is ready for a fresh walkthrough.</p></div>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <section className="overflow-hidden rounded-2xl border border-[#d8e3ec] bg-white"><div className="flex items-center justify-between border-b border-[#e2e9ef] p-5"><div><h2 className="text-sm font-semibold">Session state that will be cleared</h2><p className="mt-1 text-[10px] text-[#778a9c]">This affects the current browser session only.</p></div><span className={`rounded-full px-2.5 py-1 text-[8px] font-bold uppercase tracking-[.07em] ${clean?"bg-[#eaf8ee] text-[#2d7b4c]":"bg-[#fff3da] text-[#8d6419]"}`}>{clean?"Already clean":"Changes found"}</span></div><div className="divide-y divide-[#e7edf2]">{resetItems.map(item=>{const Icon=item.icon;return <div key={item.label} className="grid grid-cols-[40px_1fr_auto] items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-xl bg-[#edf5ff] text-[#1263e6]"><Icon size={17}/></span><div><p className="text-xs font-semibold">{item.label}</p><p className="mt-1 text-[10px] leading-4 text-[#718496]">{item.detail}</p></div><p className="text-right font-mono text-[10px] font-semibold text-[#4f687e]">{item.value}</p></div>})}</div></section>
      <div className="space-y-6"><section className="rounded-2xl border border-[#cfe2d5] bg-[#f1faf4] p-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-white text-[#338355]"><Check size={17}/></span><div><h2 className="text-sm font-semibold">What remains untouched</h2><p className="mt-1 text-[10px] text-[#66806e]">Project and provider configuration stay safe.</p></div></div><div className="mt-5 space-y-3">{["Claude API key and environment variables","Application source code and demo fixtures","Synthetic dataset and workflow definitions"].map(item=><div key={item} className="flex items-center gap-2 text-[10px] font-medium text-[#4f6d59]"><Check size={12} className="shrink-0 text-[#338355]"/>{item}</div>)}</div></section>
        <section className={`rounded-2xl border p-5 ${confirming?"border-[#e7b5ac] bg-[#fff4f2]":"border-[#dfc9c4] bg-white"}`}><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#fff0ed] text-[#c65340]"><AlertTriangle size={18}/></span><div><h2 className="text-sm font-semibold">Reset session</h2><p className="mt-1 text-[10px] leading-5 text-[#766a68]">This cannot restore approvals or released action history after they are cleared.</p></div></div>{confirming?<div data-testid="reset-confirmation" className="mt-5 rounded-xl border border-[#edc7c0] bg-white p-4"><p className="text-xs font-semibold">Reset everything now?</p><p className="mt-1 text-[10px] leading-5 text-[#786b69]">You will return to Overview with zero workflow runs and the default governance policy.</p><div className="mt-4 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button onClick={()=>setConfirming(false)} className="focus-ring flex h-10 items-center justify-center gap-2 rounded-xl border border-[#d8e1e8] px-4 text-xs font-semibold"><X size={14}/>Cancel</button><button data-testid="confirm-reset-demo" onClick={onReset} className="focus-ring flex h-10 items-center justify-center gap-2 rounded-xl bg-[#c65340] px-4 text-xs font-semibold text-white hover:bg-[#ad4434]"><RotateCcw size={14}/>Yes, reset everything</button></div></div>:<button data-testid="begin-reset-demo" onClick={()=>setConfirming(true)} disabled={clean} className="focus-ring mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#10253f] text-xs font-semibold text-white hover:bg-[#c65340] disabled:cursor-not-allowed disabled:opacity-45"><RotateCcw size={15}/>{clean?"Demo is already reset":"Reset demo"}</button>}</section>
        <section className="rounded-2xl bg-[#10253f] p-5 text-white"><Database size={18} className="text-[#6bd0f2]"/><h2 className="mt-4 text-sm font-semibold">Why this is session-only</h2><p className="mt-2 text-[10px] leading-5 text-white/60">This prototype keeps operating state in memory. Resetting clears the demonstration state; it does not delete a production system of record.</p></section>
      </div>
    </div>
  </>;
}
