"use client";

import Link from "next/link";
import { Activity, AlertTriangle, ArrowLeft, ArrowRight, Bell, Bot, Check, ChevronDown, ChevronRight, CircleDollarSign, ClipboardCheck, Clock3, Database, Gauge, Home, LoaderCircle, Mail, Menu, Play, RotateCcw, Scale, ShieldCheck, SlidersHorizontal, UserRoundCheck, Workflow as WorkflowIcon, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Brand } from "@/components/brand";
import { CohortWorkflowWorkspace, UnifiedReviewInbox } from "@/components/studio/cohort-workflow";
import { GovernanceControlPlane } from "@/components/studio/governance-control-plane";
import { OperationsOverview } from "@/components/studio/operations-overview";
import { ResetDemoPage } from "@/components/studio/reset-demo";
import { member, members, policies, workflows } from "@/lib/fixtures";
import type { AIResponse, AgentNode, HumanReview, Member, ModelStrategy, TraceEvent, Workflow } from "@/lib/types";
import { applyGovernanceToRun, defaultGovernanceConfig, getWorkflowFixture, isRecipientFacingMessage, type ActionRecord, type GovernanceConfig, type MessageDraft, type WorkflowDomainId, type WorkflowRun } from "@/lib/workflow-domain";

type View = "overview" | "workflow" | "governance" | "review" | "reset";
const nav: {id:View;label:string;icon:typeof Home}[] = [
  {id:"overview",label:"Overview",icon:Home},{id:"workflow",label:"Workflows",icon:WorkflowIcon},{id:"governance",label:"Governance",icon:ShieldCheck},{id:"review",label:"Human review",icon:ClipboardCheck},{id:"reset",label:"Reset demo",icon:RotateCcw},
];
const demoSessionKey="mission-control-demo-session-v1";
type StoredDemoSession={storageVersion:1;view:View;workflowId:string;domainRuns:Partial<Record<WorkflowDomainId,WorkflowRun>>;domainActions:ActionRecord[];governanceConfig:GovernanceConfig;governanceVersion:number};

export function StudioApp() {
  const [view,setView]=useState<View>("overview"); const [mobileOpen,setMobileOpen]=useState(false);
  const [workflow,setWorkflow]=useState(workflows[0]);
  const [running,setRunning]=useState(false);
  const [toast,setToast]=useState("");
  const [domainRuns,setDomainRuns]=useState<Partial<Record<WorkflowDomainId,WorkflowRun>>>({});
  const [domainActions,setDomainActions]=useState<ActionRecord[]>([]);
  const [governanceConfig,setGovernanceConfig]=useState<GovernanceConfig>(defaultGovernanceConfig);
  const [governanceVersion,setGovernanceVersion]=useState(2);
  const [sessionReady,setSessionReady]=useState(false);
  const sessionEpoch=useRef(0);
  const actionTimers=useRef(new Set<number>());
  useEffect(()=>{const id=window.setTimeout(()=>{try{const stored=window.sessionStorage.getItem(demoSessionKey);if(stored){const parsed=JSON.parse(stored) as StoredDemoSession;if(parsed.storageVersion===1){const restoredRuns=Object.fromEntries(Object.entries(parsed.domainRuns).map(([workflowId,run])=>[workflowId,run?{...run,candidates:run.candidates.map(candidate=>candidate.status==="sending"?{...candidate,status:"pending_review" as const}:candidate)}:run])) as Partial<Record<WorkflowDomainId,WorkflowRun>>;setDomainRuns(restoredRuns);setDomainActions(parsed.domainActions);setGovernanceConfig(parsed.governanceConfig);setGovernanceVersion(parsed.governanceVersion);const restoredWorkflow=workflows.find(item=>item.id===parsed.workflowId);if(restoredWorkflow)setWorkflow(restoredWorkflow);if(nav.some(item=>item.id===parsed.view))setView(parsed.view)}}}catch{window.sessionStorage.removeItem(demoSessionKey)}if(location.hash==="#review")setView("review");setSessionReady(true)},0);return()=>window.clearTimeout(id)},[]);
  useEffect(()=>{if(!sessionReady)return;const session:StoredDemoSession={storageVersion:1,view,workflowId:workflow.id,domainRuns,domainActions,governanceConfig,governanceVersion};try{window.sessionStorage.setItem(demoSessionKey,JSON.stringify(session))}catch{}},[sessionReady,view,workflow.id,domainRuns,domainActions,governanceConfig,governanceVersion]);
  useEffect(()=>{ if(!toast)return; const id=setTimeout(()=>setToast(""),3500); return()=>clearTimeout(id);},[toast]);
  useEffect(()=>()=>{actionTimers.current.forEach(timer=>window.clearTimeout(timer));actionTimers.current.clear()},[]);
  const chooseWorkflow=(w:Workflow)=>{setWorkflow(w);setView("workflow")};
  const runDomain=async()=>{const workflowId=workflow.id as WorkflowDomainId;const epoch=sessionEpoch.current;setRunning(true);try{const response=await fetch("/api/workflow-runs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workflowId})});if(!response.ok)throw new Error("Workflow run failed");const result=applyGovernanceToRun(await response.json() as WorkflowRun,governanceConfig);if(epoch!==sessionEpoch.current)return;setDomainRuns(current=>({...current,[workflowId]:result}));setToast(`${result.screened} ${workflowId==="membership-retention"?"members":workflowId==="community-moderation"?"posts":"events"} screened · review queue ready`)}catch{if(epoch!==sessionEpoch.current)return;const result=applyGovernanceToRun(getWorkflowFixture(workflowId),governanceConfig);setDomainRuns(current=>({...current,[workflowId]:result}));setToast("Provider unavailable · safe demo simulation loaded")}finally{if(epoch===sessionEpoch.current)setRunning(false)}};
  const decideDomain=(workflowId:WorkflowDomainId,candidateId:string,decision:"approve"|"reject",draft?:MessageDraft)=>{const candidate=domainRuns[workflowId]?.candidates.find(item=>item.id===candidateId);if(!candidate)return;if(decision==="approve"&&draft&&!isRecipientFacingMessage(candidate,draft)){setToast("Release blocked · recipient copy contains internal workflow language");return}if(decision==="reject"){setDomainRuns(current=>({...current,[workflowId]:current[workflowId]?{...current[workflowId]!,candidates:current[workflowId]!.candidates.map(item=>item.id===candidateId?{...item,status:"rejected" as const,draft:draft??item.draft}:item)}:undefined}));setToast(`Rejected · ${candidate.title} removed from the action queue`);return}setDomainRuns(current=>({...current,[workflowId]:current[workflowId]?{...current[workflowId]!,candidates:current[workflowId]!.candidates.map(item=>item.id===candidateId?{...item,status:"sending" as const,draft:draft??item.draft}:item)}:undefined}));setToast(`${workflowId==="membership-retention"?"Sending outreach":workflowId==="community-moderation"?"Applying moderation action":"Activating campaign"} for ${candidate.title}…`);const epoch=sessionEpoch.current;const timer=window.setTimeout(()=>{actionTimers.current.delete(timer);if(epoch!==sessionEpoch.current)return;setDomainRuns(current=>({...current,[workflowId]:current[workflowId]?{...current[workflowId]!,candidates:current[workflowId]!.candidates.map(item=>item.id===candidateId?{...item,status:"completed" as const,draft:draft??item.draft}:item)}:undefined}));const status:ActionRecord["status"]=workflowId==="membership-retention"?"Sent (simulated)":workflowId==="community-moderation"?"Applied (simulated)":"Active (simulated)";setDomainActions(current=>[{id:`action-${workflowId}-${candidateId}-${Date.now()}`,workflowId,candidateId,title:candidate.title,subtitle:candidate.subtitle,action:candidate.recommendation,message:draft??candidate.draft,reviewer:"Akash Sangami",status,timestamp:"Just now"},...current.filter(action=>!(action.workflowId===workflowId&&action.candidateId===candidateId))]);setToast(`${status}: ${candidate.title}`)},700);actionTimers.current.add(timer)};
  const bulkDomain=(workflowId:WorkflowDomainId,candidateIds:string[])=>{candidateIds.forEach(candidateId=>decideDomain(workflowId,candidateId,"approve",domainRuns[workflowId]?.candidates.find(candidate=>candidate.id===candidateId)?.draft))};
  const publishGovernance=(next:GovernanceConfig)=>{setGovernanceConfig(next);setGovernanceVersion(version=>version+1);setDomainRuns(current=>Object.fromEntries(Object.entries(current).map(([id,run])=>[id,run?applyGovernanceToRun(run,next):run])) as Partial<Record<WorkflowDomainId,WorkflowRun>>);setToast(`Policy v3.${governanceVersion+1} published · active queues recalculated`)};
  const resetDemo=()=>{sessionEpoch.current+=1;actionTimers.current.forEach(timer=>window.clearTimeout(timer));actionTimers.current.clear();window.sessionStorage.removeItem(demoSessionKey);setDomainRuns({});setDomainActions([]);setGovernanceConfig(defaultGovernanceConfig);setGovernanceVersion(2);setWorkflow(workflows[0]);setRunning(false);setMobileOpen(false);window.history.replaceState(null,"",window.location.pathname+window.location.search);setView("overview");setToast("Demo reset · workspace returned to its clean starting state")};
  const pendingCount=Object.values(domainRuns).reduce((count,run)=>count+(run?.candidates.filter(candidate=>candidate.status==="pending_review").length??0),0);
  return <div className="min-h-screen bg-[#f3f7fb] text-[#10253f]">
    <a href="#studio-content" className="focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-white focus:px-4 focus:py-3 sr-only focus:not-sr-only">Skip to content</a>
    <aside className={`fixed inset-y-0 left-0 z-50 w-[248px] border-r border-[#d6e0e9] bg-[#0f263f] text-white transition-transform lg:translate-x-0 ${mobileOpen?"translate-x-0":"-translate-x-full"}`}>
      <div className="flex h-[68px] items-center justify-between border-b border-white/10 px-5"><Brand light/><button className="focus-ring grid size-9 place-items-center rounded-lg hover:bg-white/10 lg:hidden" onClick={()=>setMobileOpen(false)} aria-label="Close navigation"><X size={18}/></button></div>
      <div className="px-3 py-5"><p className="px-3 text-[9px] font-bold uppercase tracking-[.15em] text-white/38">Workspace</p><nav className="mt-3 space-y-1">{nav.map(n=>{const Icon=n.icon;return <button key={n.id} onClick={()=>{setView(n.id);setMobileOpen(false)}} className={`focus-ring flex h-11 w-full items-center gap-3 rounded-xl px-3 text-left text-[13px] font-medium transition ${view===n.id?"bg-white text-[#10253f] shadow-sm":"text-white/67 hover:bg-white/8 hover:text-white"}`}><Icon size={17}/>{n.label}{n.id==="review"&&pendingCount>0&&<span className="ml-auto grid min-w-5 place-items-center rounded-full bg-[#f36f56] px-1 text-[10px] font-bold text-white">{pendingCount}</span>}</button>})}</nav></div>
      <div className="mx-3 mt-2 border-t border-white/10 pt-5"><p className="px-3 text-[9px] font-bold uppercase tracking-[.15em] text-white/38">Demo environment</p><div className="mx-2 mt-3 rounded-xl border border-[#4e7597]/50 bg-[#173651] p-3"><div className="flex items-center gap-2 text-[11px] font-semibold text-[#9ce4ff]"><span className="size-1.5 rounded-full bg-[#5ed3aa]"/>Demo Simulation</div><p className="mt-2 text-[10px] font-medium leading-4 text-white/70">Northstar Professional Association</p><p className="mt-1 text-[9px] leading-4 text-white/42">Fictional organization · Synthetic data · Safe fixture fallback</p></div></div>
      <div className="absolute bottom-0 left-0 right-0 border-t border-white/10 p-4"><Link href="/" className="focus-ring flex items-center gap-2 rounded-lg p-2 text-xs text-white/58 hover:bg-white/8 hover:text-white"><ArrowLeft size={15}/> Product site</Link><div className="mt-2 flex items-center gap-3 px-2"><span className="grid size-8 place-items-center rounded-full bg-[#2c6bb0] text-[10px] font-bold">AS</span><div><p className="text-xs font-semibold">Akash Sangami</p><p className="text-[9px] text-white/40">Studio owner</p></div></div></div>
    </aside>
    {mobileOpen&&<button className="fixed inset-0 z-40 bg-[#091a2c]/50 lg:hidden" aria-label="Close navigation backdrop" onClick={()=>setMobileOpen(false)}/>}
    <div className="lg:pl-[248px]">
      <header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-[#d9e2eb] bg-white/92 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div className="flex items-center gap-3"><button className="focus-ring grid size-9 place-items-center rounded-lg border border-[#d9e2eb] lg:hidden" onClick={()=>setMobileOpen(true)} aria-label="Open navigation"><Menu size={18}/></button><div><p className="text-[10px] text-[#788a9b]">Mission Control / <span className="text-[#1263e6]">{nav.find(n=>n.id===view)?.label}</span></p><p className="text-sm font-semibold">Northstar Professional Association</p></div></div><div className="flex items-center gap-2"><span className="hidden items-center gap-2 rounded-full border border-[#d6e9db] bg-[#eff9f1] px-3 py-1.5 text-[10px] font-semibold text-[#31774b] sm:flex"><span className="size-1.5 rounded-full bg-[#3dac68]"/>All systems operational</span><button aria-label="Notifications" className="focus-ring grid size-9 place-items-center rounded-full border border-[#dbe4ec] bg-white text-[#607387] hover:bg-[#f5f8fb]"><Bell size={16}/></button></div></header>
      <main id="studio-content" className="mx-auto max-w-[1480px] p-4 sm:p-6 lg:p-8">
        {view==="overview"&&<OperationsOverview workflows={workflows} runs={domainRuns} actions={domainActions} onChoose={chooseWorkflow} onNavigate={setView}/>}
        {view==="workflow"&&<CohortWorkflowWorkspace key={workflow.id} workflow={workflow} onWorkflow={chooseWorkflow} run={domainRuns[workflow.id as WorkflowDomainId]} running={running} onRun={runDomain} actions={domainActions} onDecision={(candidateId,decision,draft)=>decideDomain(workflow.id as WorkflowDomainId,candidateId,decision,draft)} onBulk={candidateIds=>bulkDomain(workflow.id as WorkflowDomainId,candidateIds)}/>}
        {view==="governance"&&<GovernanceControlPlane config={governanceConfig} version={governanceVersion} runs={domainRuns} onPublish={publishGovernance}/>}
        {view==="review"&&<UnifiedReviewInbox runs={domainRuns} onDecision={decideDomain}/>}
        {view==="reset"&&<ResetDemoPage runs={domainRuns} actions={domainActions} governanceVersion={governanceVersion} onReset={resetDemo}/>}
      </main>
    </div>
    {toast&&<div role="status" className="fixed bottom-5 right-5 z-[80] flex max-w-[360px] items-center gap-3 rounded-xl bg-[#10253f] px-4 py-3 text-xs font-medium text-white shadow-2xl"><Check size={16} className="text-[#71d49b]"/>{toast}</div>}
  </div>;
}

function PageHead({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:React.ReactNode}) {return <div className="mb-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.13em] text-[#1263e6]">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em] sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#66798c]">{description}</p></div>{actions}</div>}
function StatusBadge({children,tone="blue"}:{children:React.ReactNode;tone?:"blue"|"green"|"amber"|"gray"}) {const c={blue:"bg-[#e9f3ff] text-[#1263e6]",green:"bg-[#eaf8ee] text-[#2d7b4c]",amber:"bg-[#fff3da] text-[#8d6419]",gray:"bg-[#edf1f4] text-[#687a8c]"}[tone];return <span className={`inline-flex self-center justify-self-end whitespace-nowrap rounded-full px-2.5 py-1 text-[9px] font-bold uppercase leading-none tracking-[.07em] ${c}`}>{children}</span>}

export function Overview({workflows,onChoose,onNavigate,pendingCount}:{workflows:Workflow[];onChoose:(w:Workflow)=>void;onNavigate:(v:View)=>void;pendingCount:number}) {
  return <><PageHead eyebrow="Studio home" title="Welcome back." description="Monitor AI workers, review consequential decisions, and inspect performance across mission-driven workflows." actions={<div className="flex items-center gap-2 rounded-full border border-[#e7d59e] bg-[#fff8e8] px-3 py-1.5 text-[10px] text-[#806027]"><AlertTriangle size={13}/> Synthetic demo data</div>}/>
  <div className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[
    [Bot,"Active AI workers","3","+1 this month"],[Activity,"Workflow runs","1,247","Last 30 days"],[UserRoundCheck,"Human review rate","17%","Within target"],[Clock3,"Staff hours saved","83h","Estimated"],[CircleDollarSign,"Revenue protected","$38.4K","Estimated"],
  ].map(([Icon,l,v,d])=><div key={String(l)} className="last:col-span-2 rounded-2xl border border-[#dce5ed] bg-white p-4 shadow-[0_4px_16px_rgba(28,62,98,.035)] sm:p-5 lg:last:col-span-1"><div className="flex items-center justify-between"><span className="grid size-8 place-items-center rounded-lg bg-[#edf5ff] text-[#1263e6]"><Icon size={15}/></span><span className="text-[9px] text-[#8292a2]">{d as string}</span></div><p className="mt-5 font-mono text-2xl font-semibold tracking-[-.04em]">{v as string}</p><p className="mt-1 text-[11px] text-[#6f8294]">{l as string}</p></div>)}</div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_.55fr]">
    <section className="rounded-2xl border border-[#dce5ed] bg-white"><div className="flex items-center justify-between border-b border-[#e2e9ef] px-5 py-4"><div><h2 className="text-sm font-semibold">Workflow library</h2><p className="mt-1 text-[10px] text-[#8191a1]">Shared patterns across products</p></div><StatusBadge>3 workers</StatusBadge></div><div className="divide-y divide-[#e5ebf0]">{workflows.map((w,i)=><button key={w.id} onClick={()=>onChoose(w)} className="focus-ring group grid w-full grid-cols-[1fr_auto] gap-4 p-5 text-left transition hover:bg-[#f8fbff]"><div className="flex min-w-0 gap-4"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${i===0?"bg-[#1263e6] text-white":i===1?"bg-[#e8f8f4] text-[#26846c]":"bg-[#fff3e1] text-[#ad6d12]"}`}><WorkflowIcon size={18}/></span><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-semibold">{w.name}</h3><StatusBadge tone={w.status==="Active"?"green":"gray"}>{w.status}</StatusBadge></div><p className="mt-1 line-clamp-1 text-[11px] text-[#6e8193]">{w.objective}</p><p className="mt-2 text-[10px] text-[#8a99a7]">{w.nodes.length} components · {w.runs.toLocaleString()} runs</p></div></div><ArrowRight size={16} className="mt-3 text-[#9aaaba] transition group-hover:translate-x-1 group-hover:text-[#1263e6]"/></button>)}</div></section>
    <aside className="rounded-2xl border border-[#f0d6a4] bg-[#fffaf0] p-5"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-[#fff0ce] text-[#b17715]"><ClipboardCheck size={17}/></span><StatusBadge tone={pendingCount?"amber":"green"}>{pendingCount} pending</StatusBadge></div><h2 className="mt-6 text-lg font-semibold">{pendingCount?"Decisions need judgment.":"Review inbox is clear."}</h2><p className="mt-2 text-xs leading-5 text-[#756848]">{pendingCount?"Recommendations from retention, moderation, and event workflows are waiting in one governed queue.":"Run a workflow to screen its population and create evidence-backed review candidates."}</p><div className="mt-5 rounded-xl border border-[#ead9b7] bg-white/70 p-3"><p className="text-[9px] uppercase tracking-[.09em] text-[#897b60]">How this works</p><p className="mt-1 text-xs font-semibold leading-5">Screen populations → review exceptions → release approved actions</p></div><button onClick={()=>onNavigate(pendingCount?"review":"workflow")} className="focus-ring mt-5 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#10253f] text-xs font-semibold text-white hover:bg-[#1263e6]">{pendingCount?"Open review inbox":"Run a workflow"} <ArrowRight size={14}/></button></aside>
  </div></>;
}

const kindIcon={data:Database,deterministic:Gauge,agent:Bot,policy:Scale,human:UserRoundCheck,action:Mail};
const kindColor={data:"#1263e6",deterministic:"#1d9bb6",agent:"#785ed3",policy:"#db8a16",human:"#e45f49",action:"#399461"};

export function WorkflowWorkspace({workflow,onWorkflow,selected,onSelect,running,runStep,onSimulate,ai,model,onModel,activeMember,onMember,onRequestReview}:{workflow:Workflow;onWorkflow:(w:Workflow)=>void;selected:AgentNode;onSelect:(n:AgentNode)=>void;running:boolean;runStep:number;onSimulate:()=>void;ai?:AIResponse;model:ModelStrategy;onModel:(m:ModelStrategy)=>void;activeMember:Member;onMember:(member:Member)=>void;onRequestReview:(member:Member,recommendation:AIResponse)=>void}) {
  const [traceOpen,setTraceOpen]=useState<string[]>([]);
  const [actionPrepared,setActionPrepared]=useState(false);
  const runTrace=ai?.trace??[];
  const traceCost=runTrace.reduce((sum,event)=>sum+event.cost,0);
  const onNavigate=(view:View)=>{if(view==="review"&&ai)onRequestReview(activeMember,ai)};
  return <><PageHead eyebrow="Workflow builder" title={workflow.name} description={workflow.objective} actions={<div className="flex gap-2"><select aria-label="Select workflow" value={workflow.id} onChange={e=>onWorkflow(workflows.find(w=>w.id===e.target.value)!)} className="focus-ring h-10 rounded-xl border border-[#d7e1e9] bg-white px-3 text-xs font-semibold">{workflows.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select><button data-testid="run-simulation" onClick={()=>{setActionPrepared(false);onSimulate()}} disabled={running} className="focus-ring flex h-10 items-center gap-2 rounded-xl bg-[#1263e6] px-4 text-xs font-semibold text-white transition hover:bg-[#0d54c7] disabled:opacity-60">{running?<LoaderCircle className="animate-spin" size={15}/>:<Play size={14} fill="currentColor"/>}{running?"Running…":"Run simulation"}</button></div>}/>
  <div className="grid gap-5 xl:grid-cols-[1fr_310px]">
    <section className="min-w-0 overflow-hidden rounded-2xl border border-[#d8e3ec] bg-white">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e2e9ef] px-4 py-3"><div className="flex items-center gap-2"><StatusBadge tone={workflow.status==="Active"?"green":"gray"}>{workflow.status}</StatusBadge><label htmlFor="test-member" className="text-[10px] text-[#758799]">Test member</label><select id="test-member" aria-label="Select synthetic test member" value={activeMember.id} onChange={e=>onMember(members.find(candidate=>candidate.id===e.target.value)!)} className="focus-ring h-8 rounded-lg border border-[#d7e0e8] bg-[#f9fbfd] px-2 text-[10px] font-semibold">{members.map(candidate=><option key={candidate.id} value={candidate.id}>{candidate.name}</option>)}</select></div><div className="flex items-center gap-2"><label htmlFor="model" className="text-[10px] text-[#758799]">Model strategy</label><select id="model" value={model} onChange={e=>onModel(e.target.value as ModelStrategy)} className="focus-ring h-8 rounded-lg border border-[#d7e0e8] bg-[#f9fbfd] px-2 text-[10px] font-semibold"><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="deep">Deep analysis</option></select></div></div>
      <div className="relative"><span className="pointer-events-none absolute right-4 top-4 z-10 rounded-full border border-[#d5e1eb] bg-white/90 px-2.5 py-1 text-[9px] font-semibold text-[#63798d] shadow-sm sm:hidden">Swipe to inspect →</span><div className="grid-paper min-h-[420px] overflow-x-auto p-5 sm:p-8"><div className="mx-auto flex min-w-[700px] max-w-[980px] items-start pt-20">{workflow.nodes.map((n,i)=>{const Icon=kindIcon[n.kind];const active=selected.id===n.id;const processing=runStep===i&&running;const complete=runStep>i;return <div key={n.id} className="flex flex-1 items-center"><button onClick={()=>onSelect(n)} className={`focus-ring group relative flex min-h-[118px] w-full min-w-[80px] flex-col items-center justify-center rounded-2xl border bg-white px-2 py-4 text-center transition ${active?"border-[#1263e6] shadow-[0_12px_30px_rgba(18,99,230,.15)]":"border-[#d3dfe9] hover:-translate-y-1 hover:border-[#9db8d0]"} ${processing?"animate-pulse-soft":""}`}><span className="grid size-9 place-items-center rounded-xl" style={{backgroundColor:`${kindColor[n.kind]}14`,color:kindColor[n.kind]}}><Icon size={17}/></span><span className="mt-3 text-[10px] font-semibold leading-tight">{n.label}</span><span className="mt-1 text-[8px] uppercase tracking-[.08em] text-[#8796a5]">{n.kind}</span>{complete&&<span className="absolute -right-1.5 -top-1.5 grid size-5 place-items-center rounded-full bg-[#3da56a] text-white"><Check size={12}/></span>}</button>{i<workflow.nodes.length-1&&<div className="relative h-px w-3 shrink-0 bg-[#9db1c4]"><ChevronRight className="absolute -right-2 -top-[7px] text-[#7f96aa]" size={14}/></div>}</div>})}</div></div></div>
    </section>
    <Inspector node={selected}/>
  </div>
  <div className="mt-5 grid gap-5 xl:grid-cols-[.68fr_1.32fr]">
    <MemberCard member={activeMember}/>
    <section className="rounded-2xl border border-[#d8e3ec] bg-white p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold">Recommendation</h2><p className="mt-1 text-[10px] text-[#8493a2]">A proposed next step—not an automatic action</p></div>{ai?<StatusBadge tone={ai.source==="fixture"?"amber":"green"}>{ai.source==="fixture"?"Demo simulation":"Claude response"}</StatusBadge>:<StatusBadge tone="gray">Awaiting run</StatusBadge>}</div>{ai?<div className="mt-5"><div className="rounded-xl border border-[#cee0f2] bg-[#f3f8ff] p-4"><p className="text-[9px] font-bold uppercase tracking-[.1em] text-[#1263e6]">Recommended intervention</p><p className="mt-2 text-sm font-semibold leading-6">{ai.recommendedAction}</p><p className="mt-3 text-xs leading-5 text-[#64778a]">{ai.engagementShift}</p></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 text-[10px]"><span>{Math.round(ai.confidence*100)}% confidence · {ai.supportingEvidence.length} evidence signals</span><span className={`font-semibold ${ai.requiresHumanReview?"text-[#c65a3e]":"text-[#2d7b4c]"}`}>{ai.requiresHumanReview?"Human review required":"Low-risk action allowed"}</span></div><div className="mt-4 rounded-xl border border-[#dce5ed] bg-[#fafcfe] p-4"><p className="text-[9px] font-bold uppercase tracking-[.09em] text-[#718497]">What happens next</p><p className="mt-2 text-[11px] leading-5 text-[#5e7286]">{ai.requiresHumanReview?"Nothing is sent yet. Policy has routed this recommendation to an authorized person for approval, modification, or rejection.":"Policy allows this reversible, non-financial action. A user can prepare the outreach draft before anything is sent."}</p>{actionPrepared?<div role="status" className="mt-3 flex items-center gap-2 rounded-lg bg-[#eaf8ee] px-3 py-2 text-[10px] font-semibold text-[#2d7b4c]"><Check size={13}/>Outreach draft prepared for {activeMember.name}</div>:<button onClick={()=>ai.requiresHumanReview?onNavigate("review"):setActionPrepared(true)} className="focus-ring mt-3 flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-[#10253f] text-xs font-semibold text-white hover:bg-[#1263e6]">{ai.requiresHumanReview?"Review and approve":"Prepare outreach draft"}<ArrowRight size={14}/></button>}</div></div>:<EmptyState/>}</section>
  </div>
  <section className="mt-5 rounded-2xl border border-[#d8e3ec] bg-white"><div className="flex items-center justify-between border-b border-[#e2e9ef] px-5 py-4"><div><h2 className="text-sm font-semibold">Decision trace</h2><p className="mt-1 text-[10px] text-[#7d8f9f]">Run-generated summaries. Select any row to inspect its evidence.</p></div><span className="font-mono text-[10px] text-[#8292a2]">{ai?`${runTrace.reduce((sum,event)=>sum+event.latencyMs,0)}ms · $${traceCost.toFixed(3)}`:"Awaiting run"}</span></div>{ai?<div className="divide-y divide-[#e5ebf0]">{runTrace.map((t,i)=><TraceRow key={t.id} trace={t} index={i} open={traceOpen.includes(t.id)} onToggle={()=>setTraceOpen(v=>v.includes(t.id)?v.filter(x=>x!==t.id):[...v,t.id])}/>)}</div>:<div className="p-5"><div className="rounded-xl border border-dashed border-[#cad8e4] bg-[#fafcfe] px-4 py-6 text-center"><p className="text-xs font-semibold">No decision trace yet</p><p className="mt-1 text-[10px] text-[#8293a3]">Run the workflow to see which tools, evidence, and policies shaped the result.</p></div></div>}</section>
  </>;
}

function Inspector({node}:{node:AgentNode}) {const Icon=kindIcon[node.kind];return <aside className="rounded-2xl border border-[#d8e3ec] bg-white"><div className="border-b border-[#e2e9ef] p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl" style={{backgroundColor:`${kindColor[node.kind]}14`,color:kindColor[node.kind]}}><Icon size={18}/></span><StatusBadge>{node.kind}</StatusBadge></div><h2 className="mt-5 text-lg font-semibold">{node.label}</h2><p className="mt-2 text-xs leading-5 text-[#66798b]">{node.summary}</p></div><div className="space-y-4 p-5"><Info label="Execution" value={node.kind==="agent"?"Model-assisted":"Deterministic"}/><Info label="Permission scope" value={node.kind==="data"?"Read only":"Workflow scoped"}/><Info label="Failure behavior" value={node.kind==="action"?"Hold action":"Stop safely"}/><div className="rounded-xl border border-[#dfe7ed] bg-[#f8fafc] p-3"><p className="text-[9px] font-bold uppercase tracking-[.09em] text-[#758799]">Control boundary</p><p className="mt-2 text-[10px] leading-4 text-[#607487]">{node.kind==="agent"?"May recommend; cannot execute or alter policy.":node.kind==="policy"?"Rules execute outside the model.":"Uses only approved workflow inputs."}</p></div></div></aside>}
function Info({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between text-[11px]"><span className="text-[#7a8b9b]">{label}</span><span className="font-semibold">{value}</span></div>}
function MemberCard({member}:{member:Member}){const initials=member.name.split(" ").map(part=>part[0]).join("");const signed=(value:number)=>value>0?`+${value}%`:`${value}%`;return <section className="rounded-2xl border border-[#d8e3ec] bg-white p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[#deedff] text-xs font-bold text-[#1263e6]">{initials}</span><div><h2 className="text-sm font-semibold">{member.name}</h2><p className="text-[10px] text-[#7b8d9f]">{member.membership} · Renewal in {member.renewalDays} days</p></div><span className={`ml-auto font-mono text-xl font-semibold ${member.risk>=70?"text-[#d85b42]":member.risk>=50?"text-[#b87a18]":"text-[#2d8753]"}`}>{member.risk}%</span></div><div className="mt-5 grid grid-cols-2 gap-2">{[["Annual value",`$${member.annualValue}`],["Engagement",signed(member.engagementTrend)],["Events",`${member.eventsLastYear} → ${member.eventsThisYear}`],["LMS inactive",`${member.lmsInactiveDays} days`],["Community",member.communityActivity],["Career activity",signed(member.careerActivity)]].map(x=><div key={x[0]} className="rounded-lg bg-[#f5f8fb] p-3"><p className="text-[9px] text-[#8191a0]">{x[0]}</p><p className="mt-1 text-xs font-semibold">{x[1]}</p></div>)}</div></section>}
function EmptyState(){return <div className="grid min-h-36 place-items-center rounded-xl border border-dashed border-[#cad8e4] bg-[#fafcfe] text-center"><div><Play size={20} className="mx-auto text-[#8fa2b4]"/><p className="mt-2 text-xs font-semibold">Run the workflow to generate a recommendation</p><p className="mt-1 text-[10px] text-[#8293a3]">A safe fixture is available if the model is unavailable.</p></div></div>}
function TraceRow({trace,index,open,onToggle}:{trace:TraceEvent;index:number;open:boolean;onToggle:()=>void}){return <div><button onClick={onToggle} aria-expanded={open} className="focus-ring grid w-full grid-cols-[28px_1fr_auto] items-center gap-3 px-5 py-4 text-left hover:bg-[#f9fbfd]"><span className="grid size-7 place-items-center rounded-full bg-[#eaf3ff] font-mono text-[9px] font-semibold text-[#1263e6]">{index+1}</span><div><p className="text-xs font-semibold">{trace.title}</p><p className="mt-1 text-[10px] text-[#748698]">{trace.summary}</p></div><div className="flex items-center gap-4"><span className="hidden font-mono text-[9px] text-[#8192a3] sm:block">{trace.latencyMs}ms</span><ChevronDown size={15} className={`text-[#8192a3] transition ${open?"rotate-180":""}`}/></div></button>{open&&<div className="grid gap-3 bg-[#f7f9fc] px-5 py-4 sm:grid-cols-3 lg:grid-cols-6">{[["Tool",trace.tool],["Input",trace.input],["Output",trace.output],["Confidence",`${Math.round(trace.confidence*100)}%`],["Cost",trace.cost?`$${trace.cost.toFixed(3)}`:"$0"],["Evidence",trace.evidence.join(", ")]].map(x=><div key={x[0]}><p className="text-[8px] font-bold uppercase tracking-[.09em] text-[#8595a5]">{x[0]}</p><p className="mt-1 text-[9px] leading-4 text-[#455d73]">{x[1]}</p></div>)}</div>}</div>}

export function Governance(){const [threshold,setThreshold]=useState(50);const rate=Math.max(9,Math.round(26-threshold*.18));return <><PageHead eyebrow="Governance" title="Set the boundaries for autonomous action." description="Keep policy outside the model. Rules remain inspectable, testable, and consistent across recommendations."/>
<div className="grid gap-5 xl:grid-cols-[.65fr_1.35fr]"><section className="rounded-2xl border border-[#dbe4ec] bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Financial action threshold</h2><SlidersHorizontal size={17} className="text-[#1263e6]"/></div><p className="mt-2 text-[10px] leading-5 text-[#728597]">Offers at or above this amount require an authorized person.</p><div className="mt-7 flex items-end justify-between"><span className="font-mono text-3xl font-semibold">${threshold}</span><span className="text-[10px] text-[#748799]">Expected review rate <strong className="text-[#10253f]">{rate}%</strong></span></div><input aria-label="Financial review threshold" className="mt-5 w-full accent-[#1263e6]" type="range" min="25" max="100" step="5" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/><div className="mt-2 flex justify-between font-mono text-[8px] text-[#8b9aa9]"><span>$25</span><span>$100</span></div><div className="mt-7 rounded-xl border border-[#efd4a1] bg-[#fff8e9] p-4"><p className="text-[9px] font-bold uppercase text-[#976d22]">Impact preview</p><p className="mt-2 text-xs leading-5 text-[#705c38]">Sarah’s estimated ${Math.round(member.annualValue*.25)} incentive {Math.round(member.annualValue*.25)>=threshold?"still requires review":"would pass this financial rule, but confidence policy still requires review"}.</p></div></section>
<section className="overflow-hidden rounded-2xl border border-[#dbe4ec] bg-white"><div className="border-b border-[#e4eaf0] px-5 py-4"><h2 className="text-sm font-semibold">Active policy set · v3.2</h2><p className="mt-1 text-[10px] text-[#8494a4]">6 rules · Updated for this demo</p></div><div className="divide-y divide-[#e5ebf0]">{policies.map(p=><div key={p.id} className="grid grid-cols-[110px_1fr] gap-4 p-5"><StatusBadge tone={p.outcome==="Auto execute"?"green":p.outcome==="Human review"?"amber":"gray"}>{p.outcome}</StatusBadge><div><p className="text-xs font-semibold">{p.label}</p><p className="mt-1 text-[10px] leading-4 text-[#718496]">{p.detail}</p></div></div>)}</div></section></div></>}

export function ReviewQueue({review,member,evidence,onDecide,onReset,audit}:{review:HumanReview;member:Member;evidence:string[];onDecide:(s:HumanReview["status"])=>void;onReset:()=>void;audit:string[]}) {const [modifying,setModifying]=useState(false);const [note,setNote]=useState("Replace the offer with complimentary program access.");const initials=member.name.split(" ").map(part=>part[0]).join("");return <><PageHead eyebrow="Human review" title="One decision needs judgment." description="Inspect the recommendation, evidence, and policy trigger before any member-facing action is released." actions={<button onClick={onReset} className="focus-ring flex h-9 items-center gap-2 rounded-lg border border-[#d8e2ea] bg-white px-3 text-[10px] font-semibold hover:bg-[#f7f9fb]"><RotateCcw size={13}/> Reset demo</button>}/>
<div id="review" className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]"><section className="rounded-2xl border border-[#dbe4ec] bg-white"><div className="flex items-center justify-between border-b border-[#e2e9ef] p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[#e6f1ff] text-xs font-bold text-[#1263e6]">{initials}</span><div><h2 className="text-sm font-semibold">{member.name}</h2><p className="mt-1 text-[10px] text-[#7c8e9f]">{member.membership} · ${member.annualValue} annual value</p></div></div><StatusBadge tone={review.status==="Pending"?"amber":"green"}>{review.status}</StatusBadge></div><div className="p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-[9px] font-bold uppercase tracking-[.1em] text-[#7f90a0]">Recommended action</p><p className="mt-2 text-base font-semibold leading-6">{review.action}</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#f5f8fb] p-3"><p className="text-[9px] text-[#7a8c9e]">Confidence</p><p className="mt-1 font-mono text-lg font-semibold">{review.confidence}%</p></div><div className="rounded-xl bg-[#f5f8fb] p-3"><p className="text-[9px] text-[#7a8c9e]">Evidence</p><p className="mt-1 font-mono text-lg font-semibold">{review.evidenceCount} sources</p></div></div></div><div className="mt-6 rounded-xl border border-[#f0d6a5] bg-[#fff8e9] p-4"><div className="flex gap-3"><AlertTriangle size={17} className="mt-0.5 shrink-0 text-[#b17c20]"/><div><p className="text-xs font-semibold text-[#74551f]">Why this escalated</p><p className="mt-1 text-[11px] leading-5 text-[#806b45]">{review.trigger} Policies execute outside the model and cannot be bypassed by the recommendation agent.</p></div></div></div><div className="mt-6"><p className="text-[9px] font-bold uppercase tracking-[.1em] text-[#7f90a0]">Supporting evidence</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{evidence.map(item=><div key={item} className="flex items-center gap-2 rounded-lg border border-[#e0e7ee] p-3 text-[10px]"><Check size={12} className="shrink-0 text-[#36905a]"/>{item}</div>)}</div></div>
{modifying&&<div className="mt-6 rounded-xl border border-[#cdddeb] bg-[#f5f9fd] p-4"><label htmlFor="modify-note" className="text-[10px] font-semibold">Modified action</label><textarea id="modify-note" value={note} onChange={e=>setNote(e.target.value)} className="focus-ring mt-2 min-h-20 w-full resize-none rounded-lg border border-[#cfdae4] bg-white p-3 text-xs"/><div className="mt-3 flex justify-end gap-2"><button onClick={()=>setModifying(false)} className="focus-ring h-9 rounded-lg border border-[#d3dee7] px-3 text-[10px] font-semibold">Cancel</button><button onClick={()=>{setModifying(false);onDecide("Modified")}} disabled={!note.trim()} className="focus-ring h-9 rounded-lg bg-[#1263e6] px-3 text-[10px] font-semibold text-white disabled:opacity-40">Save modification</button></div></div>}
{review.status==="Pending"&&!modifying&&<div className="mt-7 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button data-testid="reject-review" onClick={()=>onDecide("Rejected")} className="focus-ring h-11 rounded-xl border border-[#e2c3bd] px-5 text-xs font-semibold text-[#b14e3b] hover:bg-[#fff3f1]">Reject</button><button onClick={()=>setModifying(true)} className="focus-ring h-11 rounded-xl border border-[#cdd9e4] px-5 text-xs font-semibold hover:bg-[#f5f8fb]">Modify</button><button data-testid="approve-review" onClick={()=>onDecide("Approved")} className="focus-ring h-11 rounded-xl bg-[#1263e6] px-6 text-xs font-semibold text-white hover:bg-[#0d54c7]">Approve & release</button></div>}
{review.status!=="Pending"&&<div className="mt-7 flex items-center gap-3 rounded-xl bg-[#edf8f1] p-4 text-xs font-semibold text-[#2f7448]"><Check size={16}/>Decision recorded: {review.status}. Outreach status updated.</div>}</div></section>
<aside className="space-y-5"><section className="rounded-2xl border border-[#dbe4ec] bg-white p-5"><h2 className="text-sm font-semibold">Activity history</h2><div className="mt-5 space-y-5">{audit.length?audit.map((a,i)=><div key={i} className="flex gap-3"><span className="mt-1 size-2 rounded-full bg-[#3ca668]"/><div><p className="text-[10px] font-semibold">{a}</p><p className="mt-1 text-[9px] text-[#8796a4]">Decision persisted to audit log</p></div></div>):<div className="rounded-xl border border-dashed border-[#d5e0e9] p-5 text-center"><Clock3 size={17} className="mx-auto text-[#8fa0b0]"/><p className="mt-2 text-[10px] text-[#788b9d]">No decision recorded yet</p></div>}</div></section><section className="rounded-2xl bg-[#10253f] p-5 text-white"><ShieldCheck size={19} className="text-[#6bd0f2]"/><h2 className="mt-5 text-sm font-semibold">Permission boundary</h2><p className="mt-2 text-[10px] leading-5 text-white/55">The recommendation agent can prepare an offer. Only an authorized reviewer can release a financial action.</p></section></aside></div></>}
